version: '3'

networks:
  default:
    driver: bridge

services:
  redis:
    image: redis:alpine
    expose:
      - "6379"

  postgres:
    image: postgres:alpine
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=homestead
      - POSTGRES_USER=homestead
      - POSTGRES_PASSWORD=qwe123asd
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - default

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPREDIS=true
        - INSTALL_BCMATH=true
        - INSTALL_OPCACHE=true
    volumes:
      - ./:/var/www:cached
    command: sh -c 'composer install; php artisan migrate; php-fpm;'
    expose:
      - "9000"
    networks:
      - default

  nginx:
    build: ./docker/nginx
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/sites/default.conf:/etc/nginx/sites-available/default.conf
      - ./docker/logs/nginx/:/var/log/nginx
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - default

  php-cli:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPREDIS=true
        - INSTALL_BCMATH=true
    volumes:
      - ./:/var/www:cached
    networks:
      - default

  node:
    image: node:10-alpine
    volumes:
      - ./:/var/www:cached
    command: sh -c 'npm install; npm run watch'
    working_dir: /var/www
    networks:
      - default

  horizon:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_REDIS=true
    volumes:
      - ./:/var/www:cached
    working_dir: /var/www
    command: php artisan horizon
    depends_on:
      - redis
      - postgres
    networks:
      - default

  scheduler:
    build:
      context: ./docker/php-cli
      args:
        - INSTALL_PHPREDIS=true
        - INSTALL_BCMATH=true
    volumes:
      - ./:/var/www:cached
      - ./docker/php-cli/scheduler.sh:/scheduler.sh
    command: sh -c "chmod +x /scheduler.sh && /scheduler.sh"
    networks:
      - default